# Generated by Django 3.2.4 on 2021-07-31 06:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Necessary', 'Necessary'), ('Normal', 'Normal'), ('Poor Priority', 'Poor Priority')], default='Normal', max_length=20, null=True)),
                ('date_of_task', models.DateTimeField()),
                ('date_create', models.DateTimeField(default=datetime.datetime.now)),
                ('active_task', models.BooleanField(default=True)),
                ('slugs', models.SlugField(blank=True, null=True, unique=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categor', to='ToDo.categories')),
            ],
            options={
                'ordering': ['date_of_task'],
            },
        ),
    ]
